version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api.space_flight
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "api.space_flight"
      VIRTUAL_PORT: 5000
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
    external_links:
      - nginx-proxy.web-base
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.build
    networks:
      - default

networks:
    default:
        name: main